version: "3.9"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=django_petshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - django_network

  web:
    build: .
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_petshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - django_network

networks:
  django_network:
    driver: bridge
